# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3da803d7fcfd9d88dba4926dd88b25ef1feb7bf855602c96a09a37f253b90eff9e29ce7ee1677dcdc55b5c666ba0a77bc1df8997fb4022495bff9ccc79ced13e

test:
  secret_key_base: 895866e710f7f4006da327f832db2a09491b7fcfedb95b91228c6f75272f57016edbc1767ff50bea64674901260c4d5d1622a2d9c7d98b1fccda1ba5f0e2888d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
